# coding: utf-8

"""
    InventoryAPI

    Orkiv Inventory API client 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import InventoryClient
from InventoryClient.rest import ApiException
from InventoryClient.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = InventoryClient.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_all_get(self):
        """
        Test case for all_get

        
        """
        pass

    def test_categories_delete(self):
        """
        Test case for categories_delete

        
        """
        pass

    def test_categories_post(self):
        """
        Test case for categories_post

        
        """
        pass

    def test_categories_put(self):
        """
        Test case for categories_put

        
        """
        pass

    def test_item_add_post(self):
        """
        Test case for item_add_post

        
        """
        pass

    def test_item_addbulk_post(self):
        """
        Test case for item_addbulk_post

        
        """
        pass

    def test_item_delete(self):
        """
        Test case for item_delete

        
        """
        pass

    def test_item_put(self):
        """
        Test case for item_put

        
        """
        pass

    def test_items_count_post(self):
        """
        Test case for items_count_post

        
        """
        pass

    def test_items_post(self):
        """
        Test case for items_post

        
        """
        pass

    def test_itemsallfields_post(self):
        """
        Test case for itemsallfields_post

        
        """
        pass

    def test_orders_post(self):
        """
        Test case for orders_post

        
        """
        pass

    def test_query_post(self):
        """
        Test case for query_post

        
        """
        pass

    def test_queryallfields_post(self):
        """
        Test case for queryallfields_post

        
        """
        pass

    def test_services_delete(self):
        """
        Test case for services_delete

        
        """
        pass

    def test_services_get(self):
        """
        Test case for services_get

        
        """
        pass

    def test_services_post(self):
        """
        Test case for services_post

        
        """
        pass

    def test_services_put(self):
        """
        Test case for services_put

        
        """
        pass

    def test_write_delete(self):
        """
        Test case for write_delete

        
        """
        pass

    def test_write_post(self):
        """
        Test case for write_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
